services:
  database_postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pgpassword
    healthcheck: #verificação da saúde do container
      test: ["CMD-SHELL", "pg_isready -U postgres"] #testa o postgres com o comando esperando uma resposta 
      interval: 5s #intervalo de tempo
      timeout: 5s #tempo maximo de espera
      retries: 5 # numero de tentativas

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - POSTGRES_HOST=database_postgres
      - POSTGRES_PASSWORD=pgpassword
    depends_on:
      database_postgres:
        condition: service_healthy #inicia o container do app só quando o postgres disser que está healthy
        
        