version: '3'

services:
  database_postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pgpassword

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database_postgres