version: '3'

services:
  database_postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pgpassword

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=database_postgres
      - POSTGRES_PASSWORD=pgpassword
    depends_on:
      - database_postgres